### ISSUE TITLE
AdaVenture

### ISSUE THREAD

**Issue by fastrgv** [BartVandewoestyne/BartVandewoestyne.github.io#1]
Hi,  I noticed you had my puzzle game AdaGate listed among other open source puzzle games for windows.  Perhaps you would consider adding my adventure game AdaVenture?

https://github.com/fastrgv/AdaVenture

It is a fairly elaborate indie game with mazes, dragons and 4 levels.  I deliver both 64-bit and 32-bit executables for Windows.
Rod (fastrgv)

**Comment by BartVandewoestyne** [comment]
Hello,

Sorry for the late reply, but I'm cleaning up my mailbox and came across
your mail :-)
I've added your game.

Kind regards,
Bart

**Comment by fastrgv** [comment]
Thx.
